# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("LoadRunner.Global.DontPromptOnEnter", false);
user_pref("LoadRunner.Global.ShowAnimations", true);
user_pref("LoadRunner.Global.ShowLineNumbers", true);
user_pref("LoadRunner.Global.SidebarOnLeft", true);
user_pref("LoadRunner.Global.SidebarWidth", 367);
user_pref("LoadRunner.Global.ToolboxY", 0);
user_pref("LoadRunner.RTS.iteration_number", 0);
user_pref("LoadRunner.config.output_dir", "C:\\Documents and Settings\\LoadRunner\\Desktop\\8_06_2013\\Khach_hang_bo.ezstore.vn_co_tranSaction_de_do\\");
user_pref("LoadRunner.config.root_dir", "C:\\PROGRA~1\\HP\\LOADRU~1");
user_pref("LoadRunner.config.runlogic_path", "C:\\Documents and Settings\\LoadRunner\\Desktop\\8_06_2013\\Khach_hang_bo.ezstore.vn_co_tranSaction_de_do\\\\default.usp");
user_pref("LoadRunner.config.user_dir", "C:\\Documents and Settings\\LoadRunner\\Desktop\\8_06_2013\\Khach_hang_bo.ezstore.vn_co_tranSaction_de_do");
user_pref("LoadRunner.sidebar.lock", true);
user_pref("accessibility.blockautorefresh", true);
user_pref("accessibility.disableenumvariant", true);
user_pref("accessibility.warn_on_browsewithcaret", false);
user_pref("advanced.system.supportDDEExec", false);
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1375761712);
user_pref("app.update.lastUpdateTime.background-update-timer", 1375761939);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1375762025);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1375673904);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1375761953);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1375673065);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.download.manager.addToRecentDocs", false);
user_pref("browser.download.manager.quitBehavior", 2);
user_pref("browser.download.manager.scanWhenDone", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.microsummary.enabled", false);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.popups.showPopupBlocker", false);
user_pref("browser.privatebrowsing.dont_prompt_on_enter", true);
user_pref("browser.privatebrowsing.keep_current_session", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.remoteLookups", false);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.search.updateinterval", -1);
user_pref("browser.sessionstore.enabled", false);
user_pref("browser.sessionstore.max_resumed_crashes", 0);
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.sessionstore.max_windows_undo", 0);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.tabs.loadOnNewTab", 0);
user_pref("browser.warnOnClose", false);
user_pref("browser.warnOnOpen", false);
user_pref("browser.warnOnQuit", false);
user_pref("browser.windows.loadOnNewWindow", 0);
user_pref("config.trim_on_minimize", false);
user_pref("dom.max_chrome_script_run_time", 60);
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.enabledItems", "TruClient@hp.com:11.00,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.3");
user_pref("extensions.lastAppVersion", "3.6.3");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("idle.lastDailyNotification", 1375763726);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("javascript.options.showInConsole", true);
user_pref("keyword.enabled", false);
user_pref("layout.css.report_errors", false);
user_pref("layout.spellcheckDefault", 0);
user_pref("metrics.upload.enable", false);
user_pref("network.automatic-ntlm-auth.allow-proxies", false);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disableIPv6", true);
user_pref("network.dnsCacheEntries", 20);
user_pref("network.dnsCacheExpiration", 3600);
user_pref("network.http.phishy-userpass-length", 255);
user_pref("network.manage-offline-status", false);
user_pref("network.prefetch-next", false);
user_pref("network.protocol-handler.external-default", false);
user_pref("network.protocol-handler.external.mailto", false);
user_pref("network.protocol-handler.external.news", false);
user_pref("network.protocol-handler.external.nntp", false);
user_pref("network.protocol-handler.external.snews", false);
user_pref("network.protocol-handler.warn-external-default", false);
user_pref("network.protocol-handler.warn-external.afp", false);
user_pref("network.protocol-handler.warn-external.data", false);
user_pref("network.protocol-handler.warn-external.disk", false);
user_pref("network.protocol-handler.warn-external.disks", false);
user_pref("network.protocol-handler.warn-external.hcp", false);
user_pref("network.protocol-handler.warn-external.javascript", false);
user_pref("network.protocol-handler.warn-external.moz-icon", false);
user_pref("network.protocol-handler.warn-external.ms-help", false);
user_pref("network.protocol-handler.warn-external.shell", false);
user_pref("network.protocol-handler.warn-external.vbscript", false);
user_pref("network.protocol-handler.warn-external.vnd.ms.radio", false);
user_pref("places.last_vacuum", 1375674538);
user_pref("plugin.default_plugin_disabled", false);
user_pref("plugin.scan.4xPluginFolder", false);
user_pref("plugin.scan.plid.all", false);
user_pref("plugin.skip_real_player_hack", true);
user_pref("plugins.hide_infobar_for_missing_plugin", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.autofillForms", false);
user_pref("signon.prefillForms", false);
